language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"
# command to install dependencies
install: "pip install -r dev_requirements.txt"
# command to run tests
script: python setup.py test
